import { RequestContext } from './context';
import { UserService } from '../services/user.service';
import { LovService } from '../services/lov.service';
import { AuthService } from '../services/auth.service';
import { CollectionService } from '../services/collection.service';
import { PmsTemplateService } from '../services/pms-template.service';
import { CycleService } from '../services/cycle.service';
import { AssignmentService } from '../services/assignment.service';
import { ObjectiveService } from '../services/objective.service';
import { EmployeeAchievementSubmissionService } from '../services/employeeAchievementSubmission.service';
import { TermReviewService } from '../services/termReview.service';
import { AnnualDecisionService } from '../services/annualDecision.service';
import { PmsCommunicationService } from '../services/pmsCommunication.service';
import { DelegationService } from '../services/delegation.service';
import { PmsDashboardService } from '../services/pmsDashboard.service';
import { PmsManagementEmployeeService } from '../services/pmsManagementEmployee.service';
import { PmsBulkOperationsService } from '../services/pmsBulkOperations.service';
import { WorkflowSyncService } from '../services/workflow-sync.service';
import { PmsDocumentService } from '../services/pms-document.service';
import { ManagerInitiatedReviewService } from '../services/managerInitiatedReview.service';
import { ProbationReviewService } from '../services/probationReview.service';
import { ManagerReviewPeriodService } from '../services/managerReviewPeriod.service';
import { ObjectiveEvidenceService } from '../services/objective-evidence.service';

export interface ServiceContainer {
  requestContext: RequestContext;
  userService: UserService;
  lovService: LovService;
  authService: AuthService;
  collectionService: CollectionService;
  pmsTemplateService: PmsTemplateService;
  cycleService: CycleService;
  assignmentService: AssignmentService;
  objectiveService: ObjectiveService;
  employeeAchievementSubmissionService: EmployeeAchievementSubmissionService;
  termReviewService: TermReviewService;
  annualDecisionService: AnnualDecisionService;
  pmsCommunicationService: PmsCommunicationService;
  delegationService: DelegationService;
  pmsDashboardService: PmsDashboardService;
  pmsManagementEmployeeService: PmsManagementEmployeeService;
  pmsBulkOperationsService: PmsBulkOperationsService;
  workflowSyncService: WorkflowSyncService;
  pmsDocumentService: PmsDocumentService;
  managerInitiatedReviewService: ManagerInitiatedReviewService;
  probationReviewService: ProbationReviewService;
  managerReviewPeriodService: ManagerReviewPeriodService;
  objectiveEvidenceService: ObjectiveEvidenceService;
}
